apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-xfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-lvm-sc-linear-xfs
